"""Build the offline UI catalog and reject missing or mismatched translations."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCES = ('i18n-static.json', 'i18n-core.json', 'i18n-rebuild.json', 'i18n-studio.json')


def build():
    messages = {}
    for source in SOURCES:
        values = json.loads((ROOT / source).read_text(encoding='utf-8'))
        for key, translations in values.items():
            tokens = set(re.findall(r'\{\w+\}', key))
            for language in ('en', 'ja'):
                value = translations.get(language)
                if not isinstance(value, str) or not value.strip():
                    raise ValueError('Missing %s translation in %s: %s' % (language, source, key))
                if set(re.findall(r'\{\w+\}', value)) != tokens:
                    raise ValueError('Mismatched parameters in %s: %s' % (source, key))
            messages.setdefault(key, translations)
    target = ROOT / 'i18n-catalog.js'
    target.write_text('/* Generated by build_i18n.py; user content is never translated. */\n'
                      + 'window.KUDIO_MESSAGES=' + json.dumps(messages, ensure_ascii=False, separators=(',', ':'))
                      + ';\n', encoding='utf-8')
    return len(messages)


if __name__ == '__main__':
    print('Built %s UI messages in English and Japanese.' % build())
