let uiOperations=0, groupEdit=null, groupsView='confirmed';
const uiBusyButtons=new Map();
const groupPalette=['#287f78','#547cc2','#ab6f3e','#8d60ac','#b25273','#4d8966','#89742b','#537f9b','#a55c49','#7470bb','#338d96','#846950'];
function groupColor(g){if(/^#[0-9a-f]{6}$/i.test(g.color||''))return g.color;let hash=0;for(const c of g.id)hash=(hash*31+c.charCodeAt(0))>>>0;return groupPalette[hash%groupPalette.length]}
function suggestionColor(g){let index=-1,chapter;for(const s of project.segments){if(s.chapter!==chapter){index++;chapter=s.chapter}if(s.id===g.start)return groupPalette[Math.max(0,index)%groupPalette.length]}return groupColor(g)}
function displayGroups(){if(!project)return [];return [...(project.groups||[]).map(g=>({...g,suggested:false})),...(project.suggestions||[]).map(g=>({...g,color:g.color||suggestionColor(g),suggested:true}))]}
function segmentMembership(ss){const result=new Map(ss.map(s=>[s.id,[]])),index=new Map(ss.map((s,i)=>[s.id,i]));for(const g of displayGroups()){const first=index.get(g.start),last=index.get(g.end);if(first===undefined||last===undefined||first>last)continue;for(let i=first;i<=last;i++)result.get(ss[i].id).push(g)}return result}
function effectiveGroups(groups){const confirmed=groups.filter(g=>!g.suggested);return confirmed.length?confirmed:groups}
function coloredBackground(groups,alpha='19'){if(!groups.length)return '#f6f8f9';if(groups.length===1)return groupColor(groups[0])+alpha;return `linear-gradient(110deg,${groups.flatMap((g,i)=>[`${groupColor(g)+alpha} ${i/groups.length*100}%`,`${groupColor(g)+alpha} ${(i+1)/groups.length*100}%`]).join(',')})`}
function decorateSegment(box,s,groups){const effective=effectiveGroups(groups);box.style.background=coloredBackground(effective);box.style.borderLeft=`4px ${effective.some(g=>g.suggested)?'dashed':'solid'} ${effective.length?groupColor(effective[0]):'#d8e0e4'}`;const labels=document.createElement('div');labels.className='membership';if(!effective.length){labels.textContent=uiText('所属分段：尚未划分')}else{const prefix=document.createElement('span');prefix.textContent=uiText('所属分段：');labels.append(prefix);for(const g of effective){const badge=document.createElement('span');badge.className='group-chip'+(g.suggested?' suggested':'');badge.style.color=groupColor(g);badge.textContent=g.suggested?uiText('建议 · {name}',{name:g.name}):g.name;labels.append(badge)}}box.append(labels)}
function jumpToSegment(index){page=Math.floor(index/20);$('segmentSearch').value='';$('filter').value='all';signature='';render();$('segments').scrollIntoView({behavior:'smooth',block:'start'})}
function renderGroupTimeline(ss,membership){const strip=$('timelineStrip');strip.replaceChildren();let run=null;const runs=[];for(let i=0;i<ss.length;i++){const groups=effectiveGroups(membership.get(ss[i].id)||[]),key=groups.map(g=>g.id).join('|');if(!run||run.key!==key){run={key,groups,start:i,end:i,duration:0};runs.push(run)}run.end=i;run.duration+=ss[i].timeline.end-ss[i].timeline.start+(i<ss.length-1?Number(project.voice.gap):0)}for(const r of runs){const b=button('',()=>jumpToSegment(r.start));b.style.flex=String(Math.max(.01,r.duration));b.style.background=coloredBackground(r.groups,'ff');b.className=r.groups.some(g=>g.suggested)?'timeline-suggestion':'timeline-confirmed';const label=r.groups.map(g=>g.suggested?uiText('建议：{name}',{name:g.name}):g.name).join(' / ')||uiText('未划分');b.title=`${label} · #${r.start+1}–#${r.end+1} · ${timecode(r.duration)}`;b.setAttribute('aria-label',b.title);strip.append(b)}const legend=$('groupLegend');legend.replaceChildren();const note=document.createElement('span');note.textContent=uiText('实色：已确认　斜纹：建议　多色：重叠分段');legend.append(note);for(const g of displayGroups()){const b=button(g.suggested?uiText('建议 · {name}',{name:g.name}):g.name,()=>{setGroupTab(g.suggested?'suggested':'confirmed');$('groupPanel').scrollIntoView({behavior:'smooth'})});b.dataset.i18nUser='true';b.uiLabel=()=>g.suggested?uiText('建议 · {name}',{name:g.name}):g.name;b.setAttribute('data-i18n-skip','');b.className='legend-chip';b.style.borderColor=groupColor(g);b.style.color=groupColor(g);legend.append(b)}}
async function runUI(b,fn){
 if(b.dataset?.busy)return;const old=b.textContent,children=Array.from(b.childNodes||b.children||[]),wasDisabled=b.disabled;
 b.dataset.busy='1';b.disabled=true;b.setAttribute('aria-busy','true');uiBusyButtons.set(b,!!old);b.textContent=old?uiText('处理中…'):'…';uiOperations++;
 try{await fn()}
 catch(e){uiErrorCount++;notify(uiText('操作失败：{error}',{error:uiText(e.message)}))}
 finally{
  uiOperations--;uiBusyButtons.delete(b);delete b.dataset.busy;b.removeAttribute('aria-busy');b.disabled=wasDisabled;
  if(typeof b.uiLabel==='function')b.textContent=b.uiLabel();
  else if(children.length){b.replaceChildren(...children);if(!b.dataset.i18nUser){for(const child of children){if(child.nodeType===3)child.textContent=uiText(child.textContent)}if(typeof KudioI18n!=='undefined')KudioI18n.localize(b)}}
  else b.textContent=b.dataset.i18nUser?old:uiText(old);
  signature='';if(!uiOperations&&!terminating&&!exited)render();
 }
}
button=function(label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=()=>runUI(b,fn);return b};
function setGroupTab(view){groupsView=view;$('groups').classList.toggle('hidden',view!=='confirmed');$('suggestedGroups').classList.toggle('hidden',view!=='suggested');$('showConfirmed').classList.toggle('tab-active',view==='confirmed');$('showSuggestions').classList.toggle('tab-active',view==='suggested')}
function resetGroupEditor(){groupEdit=null;$('groupEditStatus').textContent=uiText('新建手动分段 · 包含起止片段');$('saveGroup').textContent=uiText('保存分段');$('cancelGroupEdit').classList.add('hidden');$('groupName').value='';$('rangeStart').value='';$('rangeEnd').value='';$('groupColor').value=groupPalette[(project?.groups?.length||0)%groupPalette.length];previewRange()}
function editGroup(g){groupEdit={id:g.suggested?null:g.id,owner:project.id};$('groupName').value=g.name;$('rangeStart').value=project.segments.findIndex(s=>s.id===g.start)+1;$('rangeEnd').value=project.segments.findIndex(s=>s.id===g.end)+1;$('groupColor').value=groupColor(g);$('groupEditStatus').textContent=g.suggested?uiText('根据建议调整后另存为手动分段'):uiText('正在编辑已确认分段');$('saveGroup').textContent=uiText('保存修改');$('cancelGroupEdit').classList.remove('hidden');$('groupPanel').scrollIntoView({behavior:'smooth'});previewRange()}
function previewRange(){if(!project)return;const first=Number($('rangeStart').value),last=Number($('rangeEnd').value);if(first>=1&&last>=first&&last<=project.segments.length){const members=project.segments.slice(first-1,last);$('rangePreview').textContent=uiText('包含 {count} 个片段 · 已完成 {done} · #{first}–#{last}',{count:members.length,done:members.filter(s=>s.status==='done').length,first,last})}else{$('rangePreview').textContent=uiText('请选择有效的起止编号，可直接在片段上设置边界。')}}
function selectBoundary(which,number){$(which==='start'?'rangeStart':'rangeEnd').value=number;previewRange();notify(uiText('已将片段 #{number} 设为{boundary}；在下方保存分段',{number,boundary:uiText(which==='start'?'起点':'终点')}))}
function refreshGroupEditorLanguage(){
 $('groupEditStatus').textContent=uiText(groupEdit?(groupEdit.id?'正在编辑已确认分段':'根据建议调整后另存为手动分段'):'新建手动分段 · 包含起止片段');
 if(!$('saveGroup').dataset.busy)$('saveGroup').textContent=uiText(groupEdit?'保存修改':'保存分段');previewRange();
}
renderGroups=function(busy){const index=new Map(project.segments.map((s,i)=>[s.id,i]));const confirmed=project.groups||[],suggestions=project.suggestions||[];$('groupSummary').textContent=uiText('{count} 个已确认 · {suggested} 个待参考',{count:confirmed.length,suggested:suggestions.length});$('showConfirmed').textContent=uiText('已确认分段 ({count})',{count:confirmed.length});$('showSuggestions').textContent=uiText('自动建议 ({count})',{count:suggestions.length});for(const target of ['groups','suggestedGroups'])$(target).replaceChildren();
 for(const g of displayGroups()){const first=index.get(g.start),last=index.get(g.end),valid=first!==undefined&&last!==undefined&&first<=last;const members=valid?project.segments.slice(first,last+1):[];const row=document.createElement('div');row.className='group-card'+(g.suggested?' suggested':'');row.style.borderLeftColor=groupColor(g);const top=document.createElement('div');top.className='row';const title=document.createElement('strong');title.textContent=g.name;const tag=document.createElement('span');tag.className='badge';tag.textContent=g.suggested?uiText('自动建议 · 未采纳'):g.source==='auto'?uiText('已采纳建议'):uiText('手动分段');top.append(title,tag);const detail=document.createElement('p');detail.className='muted';const start=timeEntries[first]?.timeline,end=timeEntries[last]?.timeline;detail.textContent=valid?uiText('#{first}–#{last} · {count} 段 · 已生成 {done} 段 · {estimate}{start} — {end}',{first:first+1,last:last+1,count:members.length,done:members.filter(s=>s.status==='done').length,estimate:start.estimated||end.estimated?'≈ ':'',start:timecode(start.start),end:timecode(end.end)}):uiText('边界片段已删除，请恢复或重新调整范围');const actions=document.createElement('div');actions.className='row';
 if(g.suggested){actions.append(button(uiText('采纳为正式分段'),async()=>{await editProject('group',{name:g.name,start:g.start,end:g.end,color:groupColor(g),suggestion_id:g.id});setGroupTab('confirmed')},busy||!valid),button(uiText('调整后保存'),()=>editGroup(g),busy),button(uiText('忽略建议'),()=>editProject('dismiss-suggestion',{suggestion_id:g.id}),busy))}
 else{actions.append(button(uiText('定位片段'),()=>jumpToSegment(first),!valid),button(uiText('编辑分段'),()=>editGroup(g),busy),button(uiText('试听'),()=>playSegment(members[0].id,members.map(s=>s.id)),!valid),button(uiText('导出此分段 WAV'),()=>action('export-group',{group:g.id}),busy||!valid||members.some(s=>s.status!=='done')),button(uiText('仅导出字幕 SRT'),()=>action('export-srt',{group:g.id}),busy||!valid||members.some(s=>s.status!=='done')),button(uiText('移除分段'),()=>editProject('remove-group',{group:g.id}),busy));if(g.file)actions.append(download(g.file));if(g.srt)actions.append(download(g.srt))}row.append(top,detail,actions);$(g.suggested?'suggestedGroups':'groups').append(row)}setGroupTab(groupsView);previewRange()};
$('showConfirmed').onclick=()=>setGroupTab('confirmed');$('showSuggestions').onclick=()=>setGroupTab('suggested');$('resetSuggestions').onclick=()=>editProject('reset-suggestions');$('cancelGroupEdit').onclick=resetGroupEditor;
$('rangeStart').oninput=previewRange;$('rangeEnd').oninput=previewRange;
$('saveGroup').onclick=async()=>{if(!project)throw Error(uiText('请先选择作品'));if(groupEdit&&groupEdit.owner!==project.id)throw Error(uiText('作品已切换，请重新选择分段'));const start=Number($('rangeStart').value),end=Number($('rangeEnd').value);if(!Number.isInteger(start)||!Number.isInteger(end)||start<1||end<start||end>project.segments.length)throw Error(uiText('请输入有效的起止片段编号'));await editProject(groupEdit?.id?'update-group':'group',{group:groupEdit?.id,name:$('groupName').value,start:project.segments[start-1].id,end:project.segments[end-1].id,color:$('groupColor').value});resetGroupEditor();setGroupTab('confirmed')};
$('exportSrt').onclick=()=>action('export-srt');$('exportAll').onclick=()=>action('export-all');$('jumpGroups').onclick=()=>{$('groupPanel').scrollIntoView({behavior:'smooth'})};
const loadBeforeGroupUI=load;load=async function(id){await loadBeforeGroupUI(id);if(project?.id===id){resetGroupEditor();setGroupTab(project.groups?.length?'confirmed':'suggested')}};
// Keep existing buttons visually responsive too. Errors handled by safe() are
// counted so a rejected operation never receives a false success message.
for(const b of document.querySelectorAll('button')){if(b.onclick){const handler=b.onclick;b.onclick=(event)=>runUI(b,()=>handler.call(b,event))}}
for(const id of ['voiceForm','segmentEditForm']){const form=$(id),handler=form.onsubmit;form.onsubmit=event=>{event.preventDefault();const b=event.submitter||form.querySelector('button[type=submit]');return b?runUI(b,()=>handler(event)):handler(event)}}
// Preserve focus and hover while unchanged polling responses arrive.
const drawGroupCards=renderGroups,drawGroupTimeline=renderGroupTimeline;let cardsKey='',timelineKey='';
renderGroups=function(busy){const key=JSON.stringify([uiLocale(),project.id,project.groups,project.suggestions,busy,timeEntries.map(s=>[s.id,s.status,s.timeline])]);if(key!==cardsKey){cardsKey=key;drawGroupCards(busy)}else{setGroupTab(groupsView);previewRange()}};
renderGroupTimeline=function(ss,membership){const key=JSON.stringify([uiLocale(),project.id,displayGroups(),ss.map(s=>[s.id,s.timeline]),project.voice.gap]);if(key!==timelineKey){timelineKey=key;drawGroupTimeline(ss,membership)}};
// Boot

safe(async()=>{const turn=navigation;await list();const id=localStorage.getItem('audiobookProject');if(turn===navigation&&id&&[...$('projects').options].some(o=>o.value===id))await load(id);await loadPresets();await health()});setInterval(()=>{if(project)refresh().catch(()=>{});},2500);setInterval(health,15000);
