/* The player lives outside the refreshed segment list. A loaded Blob remains
   immutable even while the engine replaces a WAV on disk. */
let timeEntries=[], library=[], monitorPaths={}, editing=null, currentPlay=null, playQueue=[], playToken=0, nextTimer=null, waiting=false, playbackNotice='';
const player=$('continuousAudio');
function timecode(value){let ms=Math.round(Math.max(0,value||0)*1000);const hours=Math.floor(ms/3600000);ms%=3600000;const minutes=Math.floor(ms/60000);ms%=60000;return `${hours?String(hours).padStart(2,'0')+':':''}${String(minutes).padStart(2,'0')}:${String(Math.floor(ms/1000)).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`}
function button(label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=()=>safe(fn);return b}
function timeline(p){
 if(p.compilation_stale)return p.segments.map((s,i)=>({...s,number:i+1,timeline:{start:0,end:0,estimated:true}}));
 if(p.timeline?.segments){const timing=new Map(p.timeline.segments.map(s=>[s.id,s]));return p.segments.map((s,i)=>{const item=timing.get(s.id);return {...s,number:i+1,timeline:item?{start:item.start_ms/1000,end:item.end_ms/1000,estimated:item.estimated===true}:{start:0,end:0,estimated:true}}})}
 let cursor=0,exact=true;return p.segments.map((s,i)=>{const known=s.status==='done'&&s.duration>0;const duration=known?s.duration:Math.max(.5,s.text.length/4.5);const entry={...s,number:i+1,timeline:{start:cursor,end:cursor+duration,estimated:!(exact&&known)}};cursor+=duration+(i<p.segments.length-1?Number(p.voice.gap):0);exact=exact&&known;return entry});
}
function renderLibrary(){const selected=project?.id||$('projects').value,q=$('bookSearch').value.trim().toLowerCase();$('projects').replaceChildren(new Option(uiText('选择作品'),''));const visible=library.filter(p=>(!p.archived||$('showArchived').checked||p.id===selected)&&(!q||p.title.toLowerCase().includes(q)||p.id===selected));visible.forEach(p=>$('projects').add(new Option(`${p.archived?uiText('[归档] '):''}${p.title} · ${p.done}/${p.count}`,p.id)));$('projects').value=selected||'';$('libraryStats').textContent=uiText('{count} 部作品 · {archived} 部已归档',{count:library.filter(p=>!p.archived).length,archived:library.filter(p=>p.archived).length})}
list=async function(){const result=await api('state');library=result.projects;active=result.active;renderLibrary();renderTrash(result.trash||[])};
const originalLoad=load;
load=async function(id){if(id!==project?.id)stopPlayback();$('segmentSearch').value='';$('rangeStart').value='';$('rangeEnd').value='';editing=null;$('segmentEditor').close();await originalLoad(id)};
function renderStudio(stopping=false){
 if(!project||loading||terminating||exited||uiOperations)return;
 updateTrashButtons();
 const owner=project.id,ss=timeline(project),done=ss.filter(s=>s.status==='done').length,busy=active===owner;timeEntries=ss;
 $('bookTitle').textContent=project.title;$('total').textContent=ss.length;$('done').textContent=done;$('pending').textContent=ss.filter(s=>s.status==='pending').length;$('failed').textContent=ss.filter(s=>s.status==='failed').length;$('duration').textContent=(ss.reduce((n,s)=>n+(s.status==='done'?s.duration:0),0)/60).toFixed(1);$('progress').max=ss.length||1;$('progress').value=done;$('queueStatus').textContent=busy?(stopping?uiText('正在暂停'):uiText('正在生成{segment} · {count} 段运行中',{segment:ss.find(s=>s.status==='running')?' · #'+ss.find(s=>s.status==='running').number:'',count:ss.filter(s=>s.status==='running').length})):done===ss.length&&ss.length?uiText('全部完成'):uiText('队列已停止');$('projectError').textContent=project.error?uiText(project.error):'';
 $('start').disabled=!!active||!ss.some(s=>s.status==='pending');$('pause').disabled=!busy;$('retry').disabled=busy;$('export').disabled=busy||!project.groups?.length;$('exportAll').disabled=busy||!ss.length||done!==ss.length;$('exportSrt').disabled=busy||!ss.length||done!==ss.length;$('restoreDeleted').disabled=busy||!project.trash?.length;$('restoreDeleted').classList.toggle('hidden',!!project.source_format&&project.source_format!=='legacy');
 $('voiceForm').querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=busy);
 const total=ss.at(-1)?.timeline.end||0;$('timelineSummary').textContent=uiText('整书时间轴 {estimate}{time}（含段间停顿）；标有 ≈ 的位置包含未生成片段估算，生成完成后自动校准。',{estimate:ss.some(s=>s.timeline.estimated)?uiText('约 '):'',time:timecode(total)});
 const membership=segmentMembership(ss);if(!project.timeline||typeof renderScriptTimeline!=='function')renderGroupTimeline(ss,membership);
 const ex=$('exports');ex.replaceChildren();for(const file of project.exports||[])ex.append(download(file));
 renderGroups(busy||(typeof scriptIsDirty==='function'&&scriptIsDirty()));
 const query=$('segmentSearch').value.trim().toLowerCase();const filtered=ss.filter(s=>($('filter').value==='all'||s.status===$('filter').value)&&(!query||`${s.number} ${s.text} ${project.source_format==='pcs'?(s.section??''):(s.chapter??'')} ${s.role??''} ${s.voice_label??''} ${s.resolved_role_name??''} ${s.page??''}`.toLowerCase().includes(query)));
 page=Math.min(page,Math.max(0,Math.ceil(filtered.length/20)-1));const visible=filtered.slice(page*20,page*20+20);$('searchCount').textContent=uiText('匹配 {count} / {total} 段',{count:filtered.length,total:ss.length});$('pageLabel').textContent=`${page+1} / ${Math.max(1,Math.ceil(filtered.length/20))}`;$('prev').disabled=page===0;$('next').disabled=(page+1)*20>=filtered.length;
 const key=JSON.stringify([uiLocale(),visible,busy,typeof scriptIsDirty==='function'&&scriptIsDirty(),currentPlay?.id,project.groups,project.suggestions]);if(key!==signature){signature=key;const list=$('segments');list.replaceChildren();if(!visible.length){const p=document.createElement('p');p.className='empty';p.textContent=uiText('没有匹配片段');list.append(p)}
 for(const s of visible){const box=document.createElement('article');box.className='segment'+(currentPlay?.id===s.id?' playing':'');if(!project.source_format||project.source_format==='legacy')decorateSegment(box,s,membership.get(s.id)||[]);const head=document.createElement('div');head.className='segment-head';const title=document.createElement('strong');title.textContent=uiText('片段 #{number}',{number:s.number});const badge=document.createElement('span');badge.className='badge '+s.status;badge.textContent=({done:uiText('已完成'),pending:uiText('待生成'),running:uiText('生成中'),failed:uiText('失败')})[s.status];head.append(title,badge);const pos=document.createElement('div');pos.className='time';pos.textContent=`${s.timeline.estimated?'≈ ':''}${timecode(s.timeline.start)} → ${timecode(s.timeline.end)} · ${s.status==='done'?uiText('{duration} 秒',{duration:s.duration.toFixed(2)}):uiText('时长待生成')}`;const text=document.createElement('p');text.textContent=s.text;const actions=document.createElement('div');actions.className='row';actions.append(button(uiText('▶ 试听此段'),()=>playSegment(s.id),s.status!=='done'),button(uiText('参数 / 单段重做'),()=>openEditor(s.id),busy||(typeof scriptIsDirty==='function'&&scriptIsDirty())));if(!project.source_format||project.source_format==='legacy')actions.append(button(uiText('设为起点'),()=>{selectBoundary('start',s.number)}),button(uiText('设为终点'),()=>{selectBoundary('end',s.number)}),button(uiText('删除'),()=>editProject('delete-segment',{segment:s.id}),busy));if(s.previous)actions.append(button(uiText('恢复上一版'),()=>action('restore-audio',{segment:s.id}),busy));if(typeof segmentMetadata==='function'&&project.source_format&&project.source_format!=='legacy')box.append(segmentMetadata(s));box.append(head,pos,text,actions);if(s.error){const error=document.createElement('p');error.className='error';error.textContent=uiText(s.error);box.append(error)}list.append(box)}}
 if(waiting&&currentPlay&&project.segments.find(s=>s.id===currentPlay.id)?.status==='done')playSegment(currentPlay.id,playQueue);
}
function download(file){const a=document.createElement('a');a.href='/download?id='+project.id+'&file='+encodeURIComponent(file);a.download=file;a.textContent='↓ '+file;return a}
async function action(name,extra={}){const owner=project.id;await api(name,{id:owner,...extra});if(project?.id===owner){await refresh();await list()}}
async function editProject(actionName,extra={}){await action('edit-project',{action:actionName,...extra})}
function renderGroups(busy){const root=$('groups');root.replaceChildren();for(const g of project.groups||[]){const row=document.createElement('div');row.className='group-row';const first=project.segments.findIndex(s=>s.id===g.start),last=project.segments.findIndex(s=>s.id===g.end);const valid=first>=0&&last>=first;const text=document.createElement('strong');text.textContent=`${g.name} · ${valid?'#'+(first+1)+'–#'+(last+1):uiText('边界片段已删除，请恢复或重新分组')}`;const ids=valid?project.segments.slice(first,last+1).map(s=>s.id):[];row.append(text,button(uiText('试听分组'),()=>playSegment(ids[0],ids),!valid),button(uiText('导出 WAV'),()=>action('export-group',{group:g.id}),busy||!valid),button(uiText('移除分组'),()=>editProject('remove-group',{group:g.id}),busy));if(g.file)row.append(download(g.file));root.append(row)}}
function stopPlayback(){++playToken;clearTimeout(nextTimer);nextTimer=null;waiting=false;playbackNotice='';player.pause();player.removeAttribute('src');player.load();if(currentPlay?.url)URL.revokeObjectURL(currentPlay.url);currentPlay=null;playQueue=[];$('nowPlaying').textContent=uiText('尚未选择片段');$('playPosition').textContent=''}
async function playSegment(id,queue=null){
 if(!project||!id)return;const segment=project.segments.find(s=>s.id===id);if(!segment)return;
 if(segment.status!=='done'&&$('skipPending').checked){const ids=queue||project.segments.map(s=>s.id);const available=ids.slice(ids.indexOf(id)+1).find(sid=>project.segments.find(s=>s.id===sid)?.status==='done');if(available)return playSegment(available,ids);notify(uiText('此范围内没有后续已生成片段'));return}
 const oldUrl=currentPlay?.url;const token=++playToken;clearTimeout(nextTimer);player.pause();player.removeAttribute('src');player.load();waiting=false;playbackNotice='';
 playQueue=queue||project.segments.map(s=>s.id);currentPlay={id,project:project.id,url:null};if(oldUrl)URL.revokeObjectURL(oldUrl);
 const num=project.segments.indexOf(segment)+1;$('nowPlaying').textContent=`#${num} · ${segment.text.slice(0,42)}`;
 if(segment.status!=='done'){waiting=true;playbackNotice='等待此片段生成，完成后自动继续';$('playPosition').textContent=uiText(playbackNotice);return}
 try{const response=await fetch(`/audio?id=${project.id}&segment=${id}&v=${segment.audio_version||segment.duration}`);if(!response.ok)throw Error(uiText('音频文件无法读取'));const blob=await response.blob();if(token!==playToken)return;currentPlay.url=URL.createObjectURL(blob);player.src=currentPlay.url;await player.play();signature='';render()}
 catch(e){if(token===playToken){waiting=false;uiErrorCount++;notify(uiText('试听未能开始：{error}',{error:uiText(e.message)}))}}
}
async function advance(delta=1){if(!currentPlay||!project)return;let n=playQueue.indexOf(currentPlay.id)+delta;while(n>=0&&n<playQueue.length){const s=project.segments.find(s=>s.id===playQueue[n]);if(s&&(s.status==='done'||!$('skipPending').checked)){await playSegment(s.id,playQueue);return}n+=delta}waiting=false;playbackNotice='播放列表结束';$('playPosition').textContent=uiText(playbackNotice)}
player.onended=()=>{if($('continuous').checked){clearTimeout(nextTimer);nextTimer=setTimeout(()=>safe(()=>advance(1)),(typeof continuousGapMs==='function'?continuousGapMs():Math.max(0,Number(project?.voice.gap)||0)*1000))}};
function updatePlayerPosition(){if(!currentPlay||!project)return;if(playbackNotice){$('playPosition').textContent=uiText(playbackNotice);return}const segment=timeEntries.find(s=>s.id===currentPlay.id);if(segment)$('playPosition').textContent=uiText('整书位置 {estimate}{time} · 本段 {segmentTime}',{estimate:segment.timeline.estimated?'≈ ':'',time:timecode(segment.timeline.start+player.currentTime),segmentTime:timecode(player.currentTime)})}
player.ontimeupdate=updatePlayerPosition;
$('playerPrev').onclick=()=>safe(()=>advance(-1));$('playerNext').onclick=()=>safe(()=>advance(1));$('playerStop').onclick=stopPlayback;$('playAll').onclick=()=>safe(()=>{if(project?.segments.length){$('continuous').checked=true;return playSegment(project.segments[0].id)}});
$('segmentSearch').oninput=()=>{page=0;signature='';render()};$('bookSearch').oninput=renderLibrary;$('showArchived').onchange=renderLibrary;
$('restoreDeleted').onclick=()=>safe(()=>editProject('restore-segment'));
$('renameBook').onclick=()=>safe(async()=>{if(!project)return;const title=prompt(uiText('作品新名称'),project.title);if(title!==null)await editProject('rename',{title})});
$('archiveBook').onclick=()=>safe(async()=>{if(!project)return;await editProject('archive',{archived:!project.archived});notify(project.archived?uiText('作品已归档，可勾选显示归档作品查看'):uiText('作品已恢复'))});
$('saveGroup').onclick=()=>safe(async()=>{if(!project)return;const start=Number($('rangeStart').value),end=Number($('rangeEnd').value);if(!Number.isInteger(start)||!Number.isInteger(end)||start<1||end<start||end>project.segments.length)throw Error(uiText('请输入有效的起止片段编号'));await editProject('group',{name:$('groupName').value,start:project.segments[start-1].id,end:project.segments[end-1].id});notify(uiText('分组已保存'))});
function openEditor(id){const s=project.segments.find(s=>s.id===id);if(!s)return;editing={id,owner:project.id};const v={...project.voice,...s.overrides};$('editHeading').textContent=uiText('片段 #{number} · 独立参数',{number:project.segments.indexOf(s)+1});$('editText').value=s.text;$('editText').readOnly=!!project.source_format&&project.source_format!=='legacy';$('editHeading').textContent+= $('editText').readOnly?uiText(' · 正文请在脚本工作台修改'):'';$('editSpeed').value=v.speed;$('editSeed').value=v.seed;$('editLanguage').value=v.text_lang;$('editReference').value=v.reference;$('editPrompt').value=v.prompt;$('editPromptLang').value=v.prompt_lang;$('editPreset').replaceChildren(new Option(uiText('不更改参考音频'),''));presets.forEach(p=>$('editPreset').add(new Option(p.name,p.id)));$('segmentEditor').showModal()}
$('editPreset').onchange=()=>{const v=presets.find(p=>p.id===$('editPreset').value)?.voice;if(v){$('editReference').value=v.reference;$('editPrompt').value=v.prompt;$('editPromptLang').value=v.prompt_lang}};
$('randomSeed').onclick=()=>{$('editSeed').value=Math.floor(Math.random()*2147483647)};$('closeEditor').onclick=()=>{$('segmentEditor').close();editing=null};
async function submitSegment(regenerate){if(!editing)return;const target={...editing};const body={id:target.owner,segment:target.id,text:$('editText').value,overrides:{speed:Number($('editSpeed').value),seed:Number($('editSeed').value),text_lang:$('editLanguage').value,reference:$('editReference').value,prompt:$('editPrompt').value,prompt_lang:$('editPromptLang').value}};await api(regenerate?'regenerate':'edit-project',{...body,action:'edit-segment'});$('segmentEditor').close();editing=null;signature='';await refresh();notify(regenerate?uiText('仅此片段已开始重新生成'):uiText('本片段已保存为待生成'))}
$('segmentEditForm').onsubmit=e=>{e.preventDefault();return safe(()=>submitSegment(true))};$('saveSegmentEdit').onclick=()=>safe(()=>submitSegment(false));
async function reveal(path){if(!path)throw Error(uiText('路径尚未准备好'));await api('open-path',{path})}
$('openBook').onclick=()=>safe(()=>{if(project)return reveal(project.folder)});$('openData').onclick=()=>safe(()=>reveal(monitorPaths.data));$('openEngine').onclick=()=>safe(()=>reveal(monitorPaths.engine));
async function monitor(){if(exited||terminating)return;try{const data=await api('monitor');monitorPaths=data.paths;$('engineStage').textContent=uiText(data.stage);$('trainingStatus').textContent=data.training_online?uiText('官方训练面板在线'):(data.training_running?uiText('训练面板正在加载'):uiText('训练面板未连接'));for(const [id,text] of [['engineLog',data.engine_log],['trainingLog',data.training_log]]){const node=$(id),bottom=node.scrollTop+node.clientHeight>=node.scrollHeight-20;if(text)delete node.dataset.uiLogPlaceholder;else node.dataset.uiLogPlaceholder='暂无日志';const display=text||uiText('暂无日志');if(node.textContent!==display){node.textContent=display;if(bottom)node.scrollTop=node.scrollHeight}}}catch(e){$('engineStage').textContent=uiText('工作台未连接')}}
$('monitorRefresh').onclick=()=>safe(monitor);$('trainLaunch').onclick=()=>safe(async()=>{notify(uiText((await api('training',{})).message));await monitor()});
for(const id of ['engineLog','trainingLog']){const node=$(id);if(node.dataset.uiLogPlaceholder)node.textContent=uiText(node.dataset.uiLogPlaceholder)}
setInterval(()=>{if($('enginePanel').open)monitor()},4000);monitor();

// Refresh labels without reloading a work, replacing drafts or touching audio.
function refreshStudioLanguage(){
 signature='';cardsKey='';timelineKey='';
 for(const id of ['scriptVisual','executionPlan','timelineEvents'])delete $(id).dataset.renderKey;
 render();renderLibrary();renderTrash(trashedBooks);
 if(typeof refreshGroupEditorLanguage==='function')refreshGroupEditorLanguage();
 if(editing&&project?.id===editing.owner&&$('segmentEditor').open){
  const number=project.segments.findIndex(s=>s.id===editing.id)+1;
  if(number>0)$('editHeading').textContent=uiText('片段 #{number} · 独立参数',{number})+($('editText').readOnly?uiText(' · 正文请在脚本工作台修改'):'');
  const selected=$('editPreset').value;$('editPreset').replaceChildren(new Option(uiText('不更改参考音频'),''));presets.forEach(p=>$('editPreset').add(new Option(p.name,p.id)));$('editPreset').value=selected;
 }
 if(!currentPlay)$('nowPlaying').textContent=uiText('尚未选择片段');else updatePlayerPosition();
 for(const id of ['engineStage','trainingStatus'])$(id).textContent=uiText($(id).textContent);
 for(const id of ['engineLog','trainingLog']){const node=$(id);if(node.dataset.uiLogPlaceholder)node.textContent=uiText(node.dataset.uiLogPlaceholder)}
 for(const [b,hasLabel] of uiBusyButtons)b.textContent=hasLabel?uiText('处理中…'):'…';
}

// Boot after every component is installed.
